version: '3'
services:
  zenoh-bridge-server:
    build:
      context: ..
      dockerfile: server_pc/Dockerfile
    image: ros2-zenoh-bridge-server
    container_name: ros2-zenoh-bridge-server
    network_mode: "host" # Use host networking for best performance
    restart: unless-stopped
    volumes:
      - ./zenoh_server.json5:/etc/zenoh/zenoh_config.json5.template
      - ../common/entrypoint.sh:/entrypoint.sh
    env_file:
      - ../../../config/.env
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ZENOH_LISTEN_ENDPOINT=${ZENOH_LISTEN_ENDPOINT}
