version: '3'
services:
  zenoh-bridge-client:
    build:
      context: ..
      dockerfile: client_orin/Dockerfile
    image: ros2-zenoh-bridge-client
    container_name: ros2-zenoh-bridge-client
    network_mode: "host" # Use host networking for best performance and access to ROS 2 interfaces
    restart: unless-stopped
    volumes:
      - ./zenoh_client.json5:/etc/zenoh/zenoh_config.json5.template
      - ../common/entrypoint.sh:/entrypoint.sh
    env_file:
      - ../../../config/.env
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ZENOH_CONNECT_ENDPOINT=${ZENOH_CONNECT_ENDPOINT}
      - ZENOH_LISTEN_ENDPOINT=${ZENOH_LISTEN_ENDPOINT}
